name: Create weekly tags for releases
on:
  schedule:
    - cron: '0 5 * * 0' # Sunday at 5 AM UTC
    - cron: '20 13 * * *' # TEST (remove)
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "xena-${{ date }}"
          message: "Tag for xena on ${{ date }}"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "yoga-${{ date }}"
          message: "Tag for yoga on ${{ date }}"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "zed-${{ date }}"
          message: "Tag for zed on ${{ date }}"
