name: Create weekly tags for releases
on:
  schedule:
    - cron: "25 5 * * 0" # Sunday at 5:25 AM UTC
    - cron: "*/10 * * * *" # TEST (remove)
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')" # Remove time
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "xena-${{ steps.date.outputs.date }}"
          message: "Tag for xena on ${{ steps.date.outputs.date }}"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "yoga-${{ steps.date.outputs.date }}"
          message: "Tag for yoga on ${{ steps.date.outputs.date }}"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "zed-${{ steps.date.outputs.date }}"
          message: "Tag for zed on ${{ steps.date.outputs.date }}"
